### ISSUE TITLE
Not working if slot 1 and 2 are configured to something else

### ISSUE THREAD

**Issue by floviolleau** [Yubico/yubiclip-android#17] opened 2019-01-01 14:07 UTC
Hi,

I just configured my Yubikey 5 NFC on both slot 1 et 2.
- Slot 1 is configured to OATH-HOTP mode
- Slot 2 is configured to challenge-response mode

I NDEF programed for NFC to point to slot 1 with default values (uri: https://my.yubico.com/neo/)

NFC is activated and working well on my S7 Edge. I can open Yubico Authenticator when I tap the yubikey to the back of my phone in NFC.

Now, I install Yubiclip for android but when I tap the key at the back of my phone, nothing happens. No OTP are copied to the clipboard.

If I swap slot 1 and slot 2 and NDEF program to point to slot 2, I have the same issue.

Do you know why?

Thanks for your help.

Edit: Before configuring slot 1, I were able to copy OTP with Yubiclip. Anything related?

**Comment by dainnilsson** [comment] 2019-01-24 13:53
As this is being handled by the support team I'll close this issue (they should be able to get you the needed help!).
One thing to note (which might not make a difference in this case, if in fact the issue is with the YubiKey itself) is that Yubico Authenticator now supports reading the NDEF OTP as well, removing the need for having both apps. It's turned off by default though, so you need to enable it in the Yubico Authenticator settings.

**Closed by dainnilsson** 2019-01-24 13:53 UTC

**Comment by floviolleau** [comment] 2019-02-21 00:36
Hi,

Just to give you some updates.

I quickly received a new key and now it is working well :). I didn't changed anything in my setup and I reused the same secret key for OATH-HOTP to program the new key. I successfully NDEF programmed the new key.

I tried both on my laptop and on my S7 Edge phone (in NFC) and all is working perfectly.

So that it means that the previous key is bricked regarding the NDEF programming and this was the issue. I don't know how this happened...

Thanks for the help Yubico Support
